// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using StraussDa.FantasyPlayerCoreLibrary;

namespace StraussDa.FantasyPlayerCoreLibrary.Migrations
{
    [DbContext(typeof(PlayerDbContext))]
    [Migration("20190506025437_additoinalListNavigations")]
    partial class additoinalListNavigations
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.4-servicing-10062")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("StraussDa.FantasyPlayerCoreLibrary.AuctionTeam", b =>
                {
                    b.Property<int>("AuctionTeamId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("IsComplete");

                    b.Property<bool>("IsPractice");

                    b.Property<int>("RemainingBudget");

                    b.Property<int>("StartingBudget");

                    b.Property<int>("TeamSize");

                    b.Property<int>("TestUserProfileId");

                    b.HasKey("AuctionTeamId");

                    b.HasIndex("TestUserProfileId");

                    b.ToTable("AuctionTeam");
                });

            modelBuilder.Entity("StraussDa.FantasyPlayerCoreLibrary.DraftTeam", b =>
                {
                    b.Property<int>("DraftTeamId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("IsCompleted");

                    b.Property<bool>("IsPractice");

                    b.Property<string>("ScoringFormat");

                    b.Property<int>("TeamSize");

                    b.Property<int>("TestUserProfileId");

                    b.HasKey("DraftTeamId");

                    b.HasIndex("TestUserProfileId");

                    b.ToTable("DraftTeam");
                });

            modelBuilder.Entity("StraussDa.FantasyPlayerCoreLibrary.Player", b =>
                {
                    b.Property<int>("PlayerId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("PlayerImageName");

                    b.Property<string>("PlayerName");

                    b.Property<string>("PlayerPos");

                    b.Property<string>("PlayerTeam");

                    b.HasKey("PlayerId");

                    b.ToTable("Player");
                });

            modelBuilder.Entity("StraussDa.FantasyPlayerCoreLibrary.PlayerAuctioned", b =>
                {
                    b.Property<int>("PlayerAuctionedId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("AuctionTeamId");

                    b.Property<int>("PlayerId");

                    b.Property<int>("WinningBid");

                    b.HasKey("PlayerAuctionedId");

                    b.HasIndex("AuctionTeamId");

                    b.HasIndex("PlayerId");

                    b.ToTable("PlayerAuctioned");
                });

            modelBuilder.Entity("StraussDa.FantasyPlayerCoreLibrary.PlayerDrafted", b =>
                {
                    b.Property<int>("PlayerDraftedId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("DraftTeamId");

                    b.Property<int>("DraftedRound");

                    b.Property<int>("OverallPick");

                    b.Property<int>("PlayerId");

                    b.Property<int>("RoundPick");

                    b.HasKey("PlayerDraftedId");

                    b.HasIndex("DraftTeamId");

                    b.HasIndex("PlayerId");

                    b.ToTable("PlayerDrafted");
                });

            modelBuilder.Entity("StraussDa.FantasyPlayerCoreLibrary.PlayerRanking", b =>
                {
                    b.Property<int>("PlayerRankingId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("IsCustom");

                    b.Property<int>("PlayerId");

                    b.Property<int>("PlayerRank");

                    b.Property<int>("PlayerRiskLevel");

                    b.Property<decimal>("PlayerValue");

                    b.Property<int>("PosRank");

                    b.Property<int>("PprPosRank");

                    b.Property<int>("PprRank");

                    b.Property<decimal>("PprValue");

                    b.Property<int>("SflexRank");

                    b.Property<decimal>("SflexValue");

                    b.Property<int>("TestUserProfileId");

                    b.HasKey("PlayerRankingId");

                    b.HasIndex("PlayerId");

                    b.HasIndex("TestUserProfileId");

                    b.ToTable("PlayerRanking");
                });

            modelBuilder.Entity("StraussDa.FantasyPlayerCoreLibrary.TestUserProfile", b =>
                {
                    b.Property<int>("TestUserProfileId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name");

                    b.Property<string>("UserEmail");

                    b.HasKey("TestUserProfileId");

                    b.ToTable("TestUserProfile");
                });

            modelBuilder.Entity("StraussDa.FantasyPlayerCoreLibrary.AuctionTeam", b =>
                {
                    b.HasOne("StraussDa.FantasyPlayerCoreLibrary.TestUserProfile", "TestUserProfie")
                        .WithMany("AuctionTeams")
                        .HasForeignKey("TestUserProfileId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("StraussDa.FantasyPlayerCoreLibrary.DraftTeam", b =>
                {
                    b.HasOne("StraussDa.FantasyPlayerCoreLibrary.TestUserProfile", "TestUserProfie")
                        .WithMany("DraftedTeams")
                        .HasForeignKey("TestUserProfileId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("StraussDa.FantasyPlayerCoreLibrary.PlayerAuctioned", b =>
                {
                    b.HasOne("StraussDa.FantasyPlayerCoreLibrary.AuctionTeam", "AuctionTeam")
                        .WithMany("PlayersAuctioned")
                        .HasForeignKey("AuctionTeamId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("StraussDa.FantasyPlayerCoreLibrary.Player", "Player")
                        .WithMany()
                        .HasForeignKey("PlayerId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("StraussDa.FantasyPlayerCoreLibrary.PlayerDrafted", b =>
                {
                    b.HasOne("StraussDa.FantasyPlayerCoreLibrary.DraftTeam", "DraftTeam")
                        .WithMany("PlayersDrafted")
                        .HasForeignKey("DraftTeamId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("StraussDa.FantasyPlayerCoreLibrary.Player", "Player")
                        .WithMany()
                        .HasForeignKey("PlayerId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("StraussDa.FantasyPlayerCoreLibrary.PlayerRanking", b =>
                {
                    b.HasOne("StraussDa.FantasyPlayerCoreLibrary.Player", "Player")
                        .WithMany()
                        .HasForeignKey("PlayerId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("StraussDa.FantasyPlayerCoreLibrary.TestUserProfile", "TestUserProfie")
                        .WithMany("MyPlayerRanks")
                        .HasForeignKey("TestUserProfileId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
